server:
  port: 9090

spring:
  application:
    name: stats-service
  
  datasource:
    url: jdbc:postgresql://stats-db:5432/stats
    username: stats
    password: stats
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

logging:
  level:
    ru.practicum: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
